# Generated by Django 5.0.7 on 2024-07-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorytype',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
