# Generated by Django 5.0.7 on 2024-08-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0003_hashtag_gallery_hashtags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
