# Generated by Django 5.0.7 on 2024-07-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0002_initial'),
        ('products', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gallery_likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='like_users', to='galleries.gallery'),
        ),
        migrations.AlterField(
            model_name='user',
            name='product_likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='like_users', to='products.product'),
        ),
    ]
