# Generated by Django 5.0.7 on 2024-07-29 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_email_subscribed',
            new_name='subscribed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_sms_subscribed',
        ),
    ]
