# Generated by Django 5.0.7 on 2024-07-27 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_gallery_likes_alter_user_product_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='gallery_likes',
            new_name='galley_likes',
        ),
    ]
