# Generated by Django 5.0.7 on 2024-07-31 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image'),
        ('users', '0003_rename_is_email_subscribed_user_subscribed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='like_product',
        ),
        migrations.AddField(
            model_name='user',
            name='product_list',
            field=models.ManyToManyField(related_name='buyers', through='users.UserProduct', to='products.product'),
        ),
        migrations.AddField(
            model_name='userproduct',
            name='delivery',
            field=models.BooleanField(default=False),
        ),
    ]
