# Generated by Django 5.0.7 on 2024-07-27 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_gallery_likes_user_galley_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='galley_likes',
            new_name='gallery_likes',
        ),
    ]
