# Generated by Django 5.0.7 on 2024-07-31 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_like_product_user_product_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproduct',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
